"""Corpus manifests — public batch inventory (#193)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]

# Per-file read cap — same bound as admission walk (#175). Symlinks allowed
# (detect-secrets plugins/ materialization); size is the only gate here.
MAX_FILE_BYTES = 2_000_000

CORPUS_MANIFESTS: dict[str, dict[str, Any]] = {
    "json-editor": {
        "corpus_type": "validator",
        # Materialize: ln -sfn /tmp/je-check/src batch/corpora/json-editor/rules
        # JSON-schema form editor; validation regexes (URL/email/pattern)
        # on input boundaries. batch-5 triage-trial (#282).
        "path": ROOT / "batch" / "corpora" / "json-editor" / "rules",
        "glob": "**/*.js",
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "json-editor/json-editor",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "b31ddabecf4ed3209d37a2f5b29956120cd8f9ce",
        "commit": "b31ddabecf4ed3209d37a2f5b29956120cd8f9ce",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 100,
        },
    },
    "anax": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/anax-check batch/corpora/anax/rules
        # IBM Open Horizon edge agent control system. First non-dogfooding
        # posix-shell datapoint (194 shell sites). batch-5 triage-trial (#280).
        "path": ROOT / "batch" / "corpora" / "anax" / "rules",
        "glob": "**/*.sh",
        "dialect": "posix-shell",
        "extractor": "shell_posix",
        "repo": "open-horizon/anax",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "2f3fa5a506d6565fa68858b7963450567ddda114",
        "commit": "2f3fa5a506d6565fa68858b7963450567ddda114",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 500,
        },
    },
    "globussoft-crm": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/gsc-check batch/corpora/globussoft-crm/rules
        # Globussoft CRM. First-party ecma allowlist (top 60 files by probe
        # sites; excludes 14,437 vendored/test sites in node_modules/dist/
        # public/). batch-6 GO admit (#285).
        "path": ROOT / "batch" / "corpora" / "globussoft-crm" / "rules",
        "files": [
            "agentic-orchcrm/packages/tools/src/brochure/render-core.ts",
            "backend/routes/wellness.js",
            "backend/services/travelExperienceEngine.js",
            "backend/lib/mrzParser.js",
            "backend/lib/guardTeeContent.js",
            "backend/scripts/check-migration-safety.js",
            "frontend/src/pages/travel/PnlReport.jsx",
            "backend/services/pdfRenderer.js",
            "agentic-orchcrm/packages/tools/src/render.ts",
            "backend/lib/sanitizeJson.js",
            "frontend/src/pages/LandingPageBuilder.jsx",
            "backend/routes/landing_pages.js",
            "backend/lib/passportVizParser.js",
            "backend/lib/visaLetterService.js",
            "backend/services/templates/wanderlux/support.js",
            "frontend/src/pages/travel/BrochureEngine.jsx",
            "backend/routes/travel_whatsapp.js",
            "backend/services/whatsappWebClient.js",
            "frontend/src/pages/travel/Reports.jsx",
            "backend/routes/travel_microsites.js",
            "frontend/src/pages/travel/TripDetail.jsx",
            "backend/lib/landingPageGuard.js",
            "backend/scripts/cleanup-seed-pollution-2026-04-27.js",
            "frontend/src/pages/Reports.jsx",
            "backend/lib/leadJunkFilter.js",
            "frontend/src/pages/Channels.jsx",
            "scripts/audit-e2e-routes.js",
            "frontend/src/pages/WebForms.jsx",
            "backend/lib/inboundLeadVerification.js",
            "frontend/src/pages/superadmin/SuperAdminCronMaintenance.jsx",
            "frontend/src/utils/landingPageUtils.js",
            "agentic-orchcrm/packages/core/src/orchestrator/orchestrator.ts",
            "frontend/src/pages/GmailInbox.jsx",
            "frontend/src/pages/travel/CostMaster.jsx",
            "frontend/src/pages/travel/PublicTripMicrosite.jsx",
            "backend/cron/leadScoringEngine.js",
            "backend/lib/tmcReportGuard.js",
            "backend/routes/travel_quotes.js",
            "frontend/src/pages/Contacts.jsx",
            "frontend/src/pages/CustomerRegister.jsx",
            "frontend/src/pages/travel/MarketingFlyerStudio.jsx",
            "frontend/src/utils/webForms.js",
            "agentic-orchcrm/packages/providers/src/openai-compatible.ts",
            "backend/lib/validators.js",
            "backend/routes/developer.js",
            "backend/routes/travel_commission_profiles.js",
            "backend/routes/travel_diagnostics.js",
            "backend/routes/travel_invoices.js",
            "backend/routes/whatsapp.js",
            "backend/server.js",
            "backend/services/landingPageRenderer.js",
            "backend/services/passportOcrClient.js",
            "frontend/src/pages/LandingPageWanderluxEditor.jsx",
            "frontend/src/pages/travel/Itineraries.jsx",
            "frontend/src/pages/wellness/patients/PatientCreateModal.jsx",
            "backend/lib/csvEntities.js",
            "backend/lib/geminiErrors.js",
            "backend/routes/auth.js",
            "backend/routes/surveys.js",
            "backend/routes/travel_itineraries.js",
        ],
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "Globussoft-Technologies/globussoft-crm",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "8a53d8b624cacad6049d9a49255f4f8493169085",
        "commit": "8a53d8b624cacad6049d9a49255f4f8493169085",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 500,
        },
    },
    "JARVIS": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/jarvis-check batch/corpora/JARVIS/rules
        # JARVIS Trinity AGI OS. First-party py_re allowlist (top 60 py files
        # by probe sites; excludes tests/vendored). batch-6 GO admit (#286).
        "path": ROOT / "batch" / "corpora" / "JARVIS" / "rules",
        "files": [
            "backend/core/ouroboros/native_integration.py",
            "backend/context_intelligence/handlers/query_complexity_manager.py",
            "backend/context_intelligence/analyzers/intent_analyzer.py",
            "backend/context_intelligence/analyzers/action_analyzer.py",
            "backend/display/vision_ui_navigator.py",
            "backend/core/file_integrity_guardian.py",
            "backend/api/unified_command_processor.py",
            "backend/engines/nlp_engine.py",
            "backend/context_intelligence/analyzers/predictive_analyzer.py",
            "backend/voice/intelligent_command_handler.py",
            "backend/vision/screen_vision.py",
            "backend/system_control/command_safety.py",
            "backend/core/ouroboros/governance/semantic_firewall.py",
            "backend/core/ouroboros/integration.py",
            "backend/api/query_handler.py",
            "backend/core/ouroboros/governance/failure_mode_memory.py",
            "scripts/a1_graduation_auditor.py",
            "backend/context_intelligence/managers/response_strategy_manager.py",
            "backend/voice/jarvis_agent_voice.py",
            "brainstem/action_dispatcher.py",
            "backend/core/task_router.py",
            "backend/vision/multi_space_intelligence.py",
            "scripts/qwen_397b_isolation_benchmark.py",
            "backend/api/jarvis_voice_api.py",
            "backend/core/ouroboros/governance/graduation/telemetry_parse.py",
            "backend/core/ouroboros/governance/intake/sensors/vision_sensor.py",
            "backend/core/ouroboros/governance/patch_domain_guard.py",
            "backend/core/task_chain_executor.py",
            "backend/engines/rag_engine.py",
            "scripts/analyze_a1_generation.py",
            "backend/audio/conversation_pipeline.py",
            "backend/context_intelligence/handlers/math_solver.py",
            "backend/context_intelligence/resolvers/contextual_query_resolver.py",
            "backend/core/async_pipeline.py",
            "backend/core/ouroboros/governance/inline_permission.py",
            "backend/core/ouroboros/governance/intent_classifier.py",
            "backend/core/ouroboros/governance/providers.py",
            "backend/core/ouroboros/governance/semantic_guardian.py",
            "scripts/migrate_memory_topics.py",
            "scripts/trace_qwen_tool_syntax.py",
            "verify_temporal_handler_v3.py",
            "backend/autonomy/langchain_tools.py",
            "backend/core/ouroboros/governance/classify_clarify.py",
            "backend/core/ouroboros/governance/self_immunization.py",
            "backend/core/ouroboros/validator.py",
            "backend/intelligence/web_research_service.py",
            "archive/legacy/graduation_orchestrator_2026_04_06.py",
            "backend/autonomy/intelligent_learning_goals_discovery.py",
            "backend/core/data_management/unified_engine.py",
            "backend/core/ouroboros/governance/capability_firing.py",
            "backend/core/ouroboros/governance/ide_observability.py",
            "backend/core/ouroboros/governance/intake/sensors/deep_analysis_sensor.py",
            "backend/core/runtime_task_orchestrator.py",
            "backend/intelligence/context_engine.py",
            "backend/swift_bridge/python_bridge.py",
            "backend/system_control/unified_vision_weather.py",
            "backend/system_control/weather_widget_extractor.py",
            "backend/utils/weather_response_parser.py",
            "backend/vision/claude_vision_analyzer_main.py",
            "scripts/bake_jprime_golden_image.py",
        ],
        "dialect": "py_re",
        "extractor": "python_dir",
        "repo": "drussell23/JARVIS",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "d9164ff679c6f2cd3e1fa19c311db7a9eed32c7e",
        "commit": "d9164ff679c6f2cd3e1fa19c311db7a9eed32c7e",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 500,
        },
    },
    "bike4mind": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/b4m-check batch/corpora/bike4mind/rules
        # Bike4Mind AI workbench. First-party ecma allowlist (top 60 files by
        # probe sites; excludes vendored libs in public/static/lib + tests +
        # playwright config). batch-5 GO admit (#278).
        "path": ROOT / "batch" / "corpora" / "bike4mind" / "rules",
        "files": [
            "apps/client/app/utils/fileFormatUtils.ts",
            "b4m-core/utils/src/artifactElision.ts",
            "apps/client/app/utils/toolRecommender.ts",
            "apps/client/app/utils/artifactParser.ts",
            "b4m-core/utils/src/artifactParser.ts",
            "apps/client/server/services/liveopsFingerprint.ts",
            "apps/client/pages/api/admin/modal-tool.ts",
            "apps/client/app/components/Session/UserPrompt.tsx",
            "b4m-core/services/src/llm/tools/implementation/excelGeneration/xlsxTestReader.ts",
            "apps/client/server/queueHandlers/whatsNewHighlights.prompt.ts",
            "b4m-core/services/src/sreAgentService/index.ts",
            "apps/client/app/utils/codeBlockTitleExtractor.ts",
            "b4m-core/llm-adapters/src/syncModelDescriptions.ts",
            "b4m-core/services/src/llm/tools/implementation/bashExecute/index.ts",
            "packages/scripts/src/checkDeprecatedModelUsage.ts",
            "apps/client/server/services/publish/transpileReactArtifact.ts",
            "scripts/secrets-scan-summarize-and-ingest.mjs",
            "b4m-core/services/src/llm/tools/implementation/lattice/index.ts",
            "b4m-core/slack/src/thread-intelligence/patterns.ts",
            "b4m-core/utils/src/office/officeEdit.ts",
            "apps/client/server/services/liveopsTriagePrompt.ts",
            "apps/client/server/services/liveopsTriageService.ts",
            "b4m-core/mcp/src/github/tools/workflows.ts",
            "b4m-core/services/src/lib/turndown.ts",
            "b4m-core/services/src/llm/tools/implementation/excelGeneration/index.ts",
            "packages/scripts/help/utils.ts",
            "apps/client/server/integrations/slack/emailMirror.ts",
            "b4m-core/services/src/modelDiscoveryService/sources/anthropicDocs.ts",
            "b4m-core/slack/src/agent-parser.ts",
            "apps/client/app/components/admin/email/EmailTemplateEditor.tsx",
            "apps/client/app/services/adminTools/modalToolHelpers.ts",
            "apps/client/scripts/verify-overwatch-marketing-reports.sh",
            "apps/client/server/queueHandlers/whatsNewGeneration.utils.ts",
            "b4m-core/common/src/jira/format.ts",
            "b4m-core/fab-pipeline/src/chunk.ts",
            "b4m-core/services/src/modelDiscoveryService/sources/openaiDocs.ts",
            "packages/scripts/help/validate-help-content.ts",
            "apps/client/server/services/secopsTriageService.ts",
            "apps/client/server/utils/ip.ts",
            "b4m-core/common/src/queryComplexityClassifier.ts",
            "b4m-core/slack/src/handlers/channel-manager.ts",
            "packages/cli/src/utils/imageDetector.ts",
            "apps/client/app/components/admin/email/EmailJobDetail.tsx",
            "apps/client/server/queueHandlers/whatsNewGeneration.templateConstants.ts",
            "b4m-core/services/src/llm/tools/implementation/math/index.ts",
            "b4m-core/slack/src/handlers/slack-github-mapper.ts",
            "apps/client/app/components/profile/UserApiKeysTab.tsx",
            "apps/client/app/hooks/useLatticeLocalDev.ts",
            "b4m-core/common/src/confluence/format.ts",
            "apps/client/app/utils/describeUserAgent.ts",
            "apps/client/app/utils/error.ts",
            "apps/client/server/auth/trustedDevice.ts",
            "apps/client/server/queueHandlers/questExport.ts",
            "apps/client/server/services/publish/prepareShareMeta.ts",
            "apps/client/server/services/publish/viewerSecurity.ts",
            "b4m-core/common/src/utils/sanitizeTelemetryError.ts",
            "b4m-core/services/src/llm/tools/ToolValidator.ts",
            "b4m-core/services/src/notebookCurationService/formatConverter.ts",
            "packages/cli/src/tools/findDefinitionTool.ts",
            "packages/cli/src/utils/toolOutputSanitizer.ts",
        ],
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "Bike4Mind/bike4mind",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "391c37a5d7de13c9296667ceb65b3148bc276f82",
        "commit": "391c37a5d7de13c9296667ceb65b3148bc276f82",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 500,
        },
    },
    "mycelium": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/mycelium-check batch/corpora/mycelium/rules
        # Mesh networking in degrading networks. SHELL MILESTONE: 1,029
        # posix-shell sites (3.5x OpenWrt feed 713, 3.5x dogfooding 292).
        # batch-6 GO admit (#288).
        "path": ROOT / "batch" / "corpora" / "mycelium" / "rules",
        "glob": "**/*.sh",
        "dialect": "posix-shell",
        "extractor": "shell_posix",
        "repo": "mycelium0/mycelium",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "4b53dc7629ca3bc88bf5467db481ad2af7130711",
        "commit": "4b53dc7629ca3bc88bf5467db481ad2af7130711",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 500,
        },
    },
    "gitleaks": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "pilots" / "gitleaks" / "config" / "gitleaks.toml",
        "dialect": "re2",
        "extractor": "rule_file",
        "repo": "gitleaks/gitleaks",
        "security_tool": True,
        "lift_inline": True,
        "budget": {"redos_wall_s": 120},
    },
    "validatorjs": {
        "corpus_type": "validator",
        "path": ROOT / "pilots" / "validatorjs" / "src",
        # Verified domain (Phase 4): the 7-file pilot subset. Full upstream
        # src/lib inventory (~103 files) is measured separately; this manifest
        # is the declared verified domain for property execution.
        "files": [
            "isAscii.js",
            "isAlpha.js",
            "isAlphanumeric.js",
            "isEmail.js",
            "isFQDN.js",
            "isURL.js",
            "alpha.js",
        ],
        "verified_domain": "pilots/validatorjs/src/{isAscii,isAlpha,isAlphanumeric,isEmail,isFQDN,isURL,alpha}.js",
        "dialect": "ecma",
        "extractor": "js_dir",
        "repo": "validatorjs/validator.js",
        "security_tool": False,
        "lift_inline": False,
        "budget": {"redos_wall_s": 120},
    },
    "detect-secrets": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "batch" / "corpora" / "detect-secrets" / "plugins",
        "glob": "**/*.py",
        "dialect": "py_re",
        "extractor": "python_dir",
        "repo": "Yelp/detect-secrets",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "v1.5.0",
        "commit": "01886c8a910c64595c47f186ca1ffc0b77fa5458",
        "budget": {"redos_wall_s": 60},
    },
    "coreruleset": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "batch" / "corpora" / "coreruleset" / "rules",
        "dialect": "pcre",
        "extractor": "modsec",
        "repo": "coreruleset/coreruleset",
        "security_tool": True,
        "lift_inline": True,
        "budget": {"redos_wall_s": 180},
    },
    "trufflehog": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "batch" / "corpora" / "trufflehog" / "detectors",
        "glob": "**/*.go",
        "dialect": "re2",
        "extractor": "go_regexp",
        "repo": "trufflesecurity/trufflehog",
        "security_tool": True,
        "lift_inline": True,
        "corpus_pin": "v3.88.29",
        "commit": "90190deac64289cb10bb694894be8db9ead8790b",
        "budget": {"max_patterns": 5000, "max_wall_s": 600, "redos_wall_s": 120, "max_mem_mb": 1024, "max_disk_mb": 100},
    },
    "ids_rules": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "batch" / "corpora" / "ids_rules" / "rules",
        "glob": "*.rules",
        "dialect": "pcre",
        "extractor": "ids_rules",
        "repo": "emergingthreats/open",
        "security_tool": True,
        "lift_inline": True,
        "corpus_pin": "suricata-7.0.3-et-open",
        "commit": "emergingthreats-open-suricata-7.0.3",
        "budget": {"max_patterns": 20000, "max_wall_s": 900, "redos_wall_s": 180, "max_mem_mb": 2048, "max_disk_mb": 200},
    },
    "semgrep_rules": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "batch" / "corpora" / "semgrep_rules" / "rules",
        "glob": "**/*.yml,**/*.yaml",
        # Semgrep evaluates pattern-regex via rust `regex` crate; stock path
        # is an ASCII approximation (declared + fidelity-fuzzed).
        "dialect": "py_re",
        "declared_semantics": "ascii_approx_rust_regex",
        "extractor": "semgrep_yaml",
        "repo": "semgrep/semgrep-rules",
        "security_tool": True,
        "lift_inline": True,
        "corpus_pin": "40b8c63f75dc7c22c8a77482d73bfb864b146f7e",
        "commit": "40b8c63f75dc7c22c8a77482d73bfb864b146f7e",
        "budget": {"max_patterns": 5000, "max_wall_s": 600, "redos_wall_s": 120, "max_mem_mb": 1024, "max_disk_mb": 100},
    },
    "re2_testdata": {
        "corpus_type": "testdata",
        "path": ROOT / "batch" / "corpora" / "re2_testdata" / "testdata",
        "full_path": ROOT / "batch" / "corpora" / "re2_testdata" / "testdata",
        "sample_path": ROOT / "batch" / "corpora" / "re2_testdata" / "sample",
        "glob": "*.txt",
        "dialect": "re2",
        "extractor": "re2_testdata",
        "repo": "google/re2",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "2024-07-02",
        "measure_scope": "sample",
        "budget": {"max_patterns": 5000, "max_wall_s": 300, "max_mem_mb": 512, "max_disk_mb": 50},
    },
    "pcre2_testdata": {
        "corpus_type": "testdata",
        "path": ROOT / "batch" / "corpora" / "pcre2_testdata" / "testdata",
        "full_path": ROOT / "batch" / "corpora" / "pcre2_testdata" / "testdata",
        "sample_path": ROOT / "batch" / "corpora" / "pcre2_testdata" / "sample",
        "glob": "testinput*",
        "dialect": "pcre",
        "extractor": "pcre2_testdata",
        "repo": "PCRE2Project/pcre2",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "pcre2-10.44",
        "measure_scope": "sample",
        "budget": {"max_patterns": 20000, "max_wall_s": 900, "max_mem_mb": 1024, "max_disk_mb": 100},
    },
    "cpython_re": {
        "corpus_type": "testdata",
        "path": ROOT / "batch" / "corpora" / "cpython_re",
        "full_path": ROOT / "batch" / "corpora" / "cpython_re",
        "sample_path": ROOT / "batch" / "corpora" / "cpython_re" / "re_tests.py",
        "glob": "*.py",
        "dialect": "py_re",
        "extractor": "cpython_re_tests",
        "repo": "python/cpython",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "v3.12.8",
        "measure_scope": "sample",
        "budget": {"max_patterns": 5000, "max_wall_s": 300, "max_mem_mb": 512, "max_disk_mb": 50},
    },
    "busybox": {
        "corpus_type": "testdata",
        "path": ROOT / "batch" / "corpora" / "busybox" / "testsuite",
        "full_path": ROOT / "batch" / "corpora" / "busybox" / "testsuite",
        "sample_path": ROOT / "batch" / "corpora" / "busybox" / "sample",
        "glob": "*.tests,**/*.tests",
        "dialect": "pcre",
        "extractor": "busybox_tests",
        "repo": "mirror/busybox",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "1_36_1",
        "measure_scope": "sample",
        "budget": {"max_patterns": 5000, "max_wall_s": 300, "max_mem_mb": 512, "max_disk_mb": 50},
    },
    "rust_regex": {
        "corpus_type": "inventory_only",
        "path": ROOT / "batch" / "corpora" / "rust_regex" / "sample",
        "dialect": "rust_regex",
        "extractor": "rust_inventory",
        "repo": "rust-lang/regex",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "1.11.1",
        "measure_scope": "sample",
        "budget": {"max_patterns": 0, "max_wall_s": 60},
    },
    "yara_rules": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "batch" / "corpora" / "yara_rules" / "rules",
        "glob": "**/*.yar,**/*.yara",
        "dialect": "yara",
        "extractor": "yara",
        "repo": "YARA-Rules/rules",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "0f93570194a80d2f2032869055808b0ddcdfb360",
        "commit": "0f93570194a80d2f2032869055808b0ddcdfb360",
        # Full clone ~17.5k string sites; 5k was pre-enforcement decorative.
        "budget": {"max_patterns": 25000, "max_wall_s": 600, "redos_wall_s": 120, "max_mem_mb": 1024, "max_disk_mb": 100},
    },
    "test262": {
        "corpus_type": "testdata",
        "path": ROOT / "batch" / "corpora" / "test262" / "RegExp",
        "full_path": ROOT / "batch" / "corpora" / "test262" / "RegExp",
        "sample_path": ROOT / "batch" / "corpora" / "test262" / "sample",
        "glob": "**/*.js",
        "dialect": "ecma",
        "extractor": "test262",
        "repo": "tc39/test262",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "be13516fb6441b950ba8a3df97eb34062c186972",
        "expected_files": 1879,
        "measure_scope": "sample",
        "budget": {"max_patterns": 20000, "max_wall_s": 900, "max_mem_mb": 1024, "max_disk_mb": 200},
    },
    "spamassassin": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "batch" / "corpora" / "spamassassin" / "rules",
        "glob": "**/*.cf",
        "dialect": "perl",
        "extractor": "spamassassin",
        "repo": "apache/spamassassin",
        "security_tool": True,
        "lift_inline": True,
        "corpus_pin": "17e7842caa629d032589458f86d2f5ce8e7306a4",
        "commit": "17e7842caa629d032589458f86d2f5ce8e7306a4",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 100,
        },
    },
    "noseyparker": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "batch" / "corpora" / "noseyparker" / "rules",
        "glob": "**/*.yml",
        # re2 is a declared approximation of rust regex (see
        # sweep/corpus-wave3/noseyparker-dialect.md); differential-fuzz vs go-re2.
        "dialect": "re2",
        "declared_semantics": "ascii_approx_rust_regex",
        "extractor": "noseyparker",
        "repo": "praetorian-inc/noseyparker",
        "security_tool": True,
        "lift_inline": True,
        "corpus_pin": "2e6e7f36ce36619852532bbe698d8cb7a26d2da7",
        "commit": "2e6e7f36ce36619852532bbe698d8cb7a26d2da7",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 100,
        },
    },
    "shhgit": {
        "corpus_type": "rule_corpus",
        "path": ROOT / "batch" / "corpora" / "shhgit" / "repo",
        "glob": "config.yaml",
        "files": ["config.yaml"],
        "dialect": "re2",
        "extractor": "shhgit",
        "repo": "eth0izzle/shhgit",
        "security_tool": True,
        # Leading (?i) in content signatures; mid (?-i) remains inline-flag.
        "lift_inline": True,
        "corpus_pin": "bac0c7d39519203d230b6c9a2c6e3eba18346aba",
        "commit": "bac0c7d39519203d230b6c9a2c6e3eba18346aba",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 300,
            "redos_wall_s": 60,
            "max_mem_mb": 512,
            "max_disk_mb": 50,
        },
    },
    "dompurify": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/DOMPurify batch/corpora/dompurify/rules
        # (gitignored). TS sources are listed explicitly — js_dir globs *.js only.
        "path": ROOT / "batch" / "corpora" / "dompurify" / "rules",
        "files": [
            "src/purify.ts",
            "src/regexp.ts",
            "src/attrs.ts",
            "src/tags.ts",
            "src/utils.ts",
        ],
        "dialect": "ecma",
        "extractor": "dompurify",
        "repo": "cure53/DOMPurify",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "7392211bda80f9c1038db32fc090119685bfe425",
        "commit": "7392211bda80f9c1038db32fc090119685bfe425",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 300,
            "redos_wall_s": 60,
            "max_mem_mb": 512,
            "max_disk_mb": 50,
        },
    },
    "isemail": {
        "corpus_type": "validator",
        "path": ROOT / "batch" / "corpora" / "isemail" / "rules",
        "files": [
            "constants.js",
            "diagnoses.js",
            "index.js",
            "parser.js",
            "reader.js",
            "utils.js",
            "validation.js",
        ],
        "dialect": "ecma",
        "extractor": "isemail",
        "repo": "hapijs/isemail",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "8789d509d69f098350783fb2d8d2bf05f036b448",
        "commit": "8789d509d69f098350783fb2d8d2bf05f036b448",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 300,
            "redos_wall_s": 60,
            "max_mem_mb": 512,
            "max_disk_mb": 50,
        },
    },
    "email_addresses": {
        "corpus_type": "validator",
        "path": ROOT / "batch" / "corpora" / "email_addresses" / "rules",
        "files": ["email-addresses.js"],
        "dialect": "ecma",
        "extractor": "email_addresses",
        "repo": "jackbearheart/email-addresses",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "8e6be27770b7be223c2de035d7e52849f938c959",
        "commit": "8e6be27770b7be223c2de035d7e52849f938c959",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 300,
            "redos_wall_s": 60,
            "max_mem_mb": 512,
            "max_disk_mb": 50,
        },
    },
    "hippo": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/hippo batch/corpora/hippo/rules
        # Explicit allowlist — probe 2899 sites are dominated by vendored bundles.
        "path": ROOT / "batch" / "corpora" / "hippo" / "rules",
        "files": [
            "repository-data/webfiles/src/main/resources/site/src/js/eforms/eforms.js",
            "repository-data/webfiles/src/main/resources/site/src/js/eforms/formcheck/formcheck.js",
            "repository-data/webfiles/src/main/resources/site/src/js/eforms/jquery-hippo-validate.js",
            "repository-data/webfiles/src/main/resources/site/src/js/table-sort/table-sort-date.js",
            "repository-data/webfiles/src/main/resources/site/src/js/statistics/statistics-countup.js",
            "repository-data/webfiles/src/main/resources/site/src/js/utils/vanilla-js-utils.js",
        ],
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "NHS-digital-website/hippo",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "4879bd48c50c712236f99413cb1f68091cea599c",
        "commit": "4879bd48c50c712236f99413cb1f68091cea599c",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 200,
        },
    },
    "everclaw-community-branches": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/everclaw batch/corpora/everclaw-community-branches/rules
        # Exclude docs/docs/assets bundled JS; prefer skillguard + first-party scripts.
        "path": ROOT / "batch" / "corpora" / "everclaw-community-branches" / "rules",
        "files": [
            "skills/skillguard/src/ast-analyzer.js",
            "skills/skillguard/src/clawhub.js",
            "skills/skillguard/src/cli.js",
            "skills/skillguard/src/diff-scanner.js",
            "skills/skillguard/src/flow-analyzer.js",
            "skills/skillguard/src/gate.js",
            "skills/skillguard/src/prompt-analyzer.js",
            "skills/skillguard/src/runtime-monitor.js",
            "skills/skillguard/src/scanner.js",
            "skills/relationships/scripts/relationship.mjs",
            "packages/core/auth-proxy/server.mjs",
            "scripts/agent-download-server.mjs",
            "scripts/agent-download.mjs",
            "scripts/agent-registry.mjs",
            "scripts/bootstrap-client.mjs",
            "scripts/bootstrap-everclaw.mjs",
            "scripts/bootstrap-gateway.mjs",
            "scripts/coingecko-x402.mjs",
            "scripts/everclaw-deps.mjs",
            "scripts/everclaw-export.mjs",
            "scripts/everclaw-migrate.mjs",
            "scripts/everclaw-restore.mjs",
            "scripts/everclaw-verify.mjs",
            "scripts/everclaw-wallet.mjs",
            "scripts/inference-balance-tracker.mjs",
            "scripts/morpheus-proxy.mjs",
            "scripts/morpheus-session-mgr.mjs",
            "scripts/router.mjs",
            "scripts/safe-transfer.mjs",
            "scripts/security-tier.mjs",
            "scripts/setup.mjs",
            "scripts/x402-client.mjs",
            "scripts/lib/docker.mjs",
            "scripts/lib/encryption.mjs",
            "scripts/lib/file-backend.mjs",
            "scripts/lib/keychain.mjs",
            "scripts/lib/manifest.mjs",
            "scripts/lib/morpheus.mjs",
            "scripts/lib/verify.mjs",
            "mission-control/generate-data.mjs",
        ],
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "profbernardoj/everclaw-community-branches",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "7ea3b445ee7d2ef8004d5ee77dab7544e1b8ef88",
        "commit": "7ea3b445ee7d2ef8004d5ee77dab7544e1b8ef88",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 200,
        },
    },
    "tracecat": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/tracecat batch/corpora/tracecat/rules
        # Product py_re only (exclude tests + benchmark packages).
        "path": ROOT / "batch" / "corpora" / "tracecat" / "rules",
        "files": [
            "tracecat/agent/adapter/vercel.py",
            "tracecat/agent/channels/handlers/slack.py",
            "tracecat/agent/mcp/utils.py",
            "tracecat/agent/runtime/claude_code/runtime.py",
            "tracecat/agent/sandbox/config.py",
            "tracecat/agent/sandbox/llm_proxy.py",
            "tracecat/authz/controls.py",
            "tracecat/cases/service.py",
            "tracecat/dsl/workflow.py",
            "tracecat/editor/router.py",
            "tracecat/executor/secret_preprocessors.py",
            "tracecat/expressions/functions.py",
            "tracecat/expressions/ioc_extractors/domain.py",
            "tracecat/expressions/patterns.py",
            "tracecat/expressions/validator/validator.py",
            "tracecat/git/constants.py",
            "tracecat/identifiers/workflow.py",
            "tracecat/integrations/catalog/loader.py",
            "tracecat/integrations/mcp_validation.py",
            "tracecat/integrations/providers/microsoft/common.py",
            "tracecat/integrations/service.py",
            "tracecat/mcp/auth.py",
            "tracecat/mcp/schemas.py",
            "tracecat/middleware/request.py",
            "tracecat/parse.py",
            "tracecat/registry/artifact_keys.py",
            "tracecat/registry/dependencies.py",
            "tracecat/registry/repository.py",
            "tracecat/registry/sync/jobs.py",
            "tracecat/sandbox/executor.py",
            "tracecat/sanitization.py",
            "tracecat/secrets/common.py",
            "tracecat/tables/common.py",
            "tracecat/tables/schemas.py",
            "tracecat/workflow/executions/schemas.py",
            "tracecat/workflow/management/management.py",
            "tracecat/workflow/store/schemas.py",
            "tracecat/workspace_sync/adapters/base.py",
            "tracecat/workspace_sync/service.py",
            "packages/tracecat-registry/tracecat_registry/core/email.py",
        ],
        "dialect": "py_re",
        "extractor": "python_dir",
        "repo": "TracecatHQ/tracecat",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "c84d52528a489821f355fc63976fbc7783ae0ad5",
        "commit": "c84d52528a489821f355fc63976fbc7783ae0ad5",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 200,
        },
    },
    "octo-server": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/octo-server batch/corpora/octo-server/rules
        # Exclude assets/web/js/jquery*.min.js and *_test.go.
        "path": ROOT / "batch" / "corpora" / "octo-server" / "rules",
        "files": [
            "internal/cardactiondispatch/registry.go",
            "internal/carddispatch/registry.go",
            "modules/app_bot/app_bot.go",
            "modules/bot_api/commands.go",
            "modules/card_template_catalog/api_state.go",
            "modules/common/api.go",
            "modules/common/system_settings.go",
            "modules/oidc/api.go",
            "modules/oidc/config.go",
            "modules/openapi/api.go",
            "modules/robot/api.go",
            "modules/sticker/model.go",
            "pkg/accesslog/accesslog.go",
            "pkg/cardmsg/inputs.go",
            "pkg/cardtmpl/approval_request.go",
            "pkg/cardtmpl/json_artifact.go",
            "pkg/i18n/codes/registry.go",
            "pkg/i18n/params.go",
            "pkg/space/channel.go",
            "tools/migrate-rename/main.go",
            "tools/migrate-rename/rewrite_initdb.go",
        ],
        "dialect": "re2",
        "extractor": "go_regexp",
        "repo": "Mininglamp-OSS/octo-server",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "d3daa912a04d17f78df2d0c059a111cafff75534",
        "commit": "d3daa912a04d17f78df2d0c059a111cafff75534",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 200,
        },
    },
    "magic-js": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/magic-js batch/corpora/magic-js/rules
        # Prefer packages/@magic-*; exclude .yarn plugins and rollup configs.
        "path": ROOT / "batch" / "corpora" / "magic-js" / "rules",
        "files": [
            "packages/@magic-ext/farcaster/src/utils.ts",
            "packages/@magic-ext/oauth2/src/crypto.ts",
            "packages/@magic-ext/oauth2/src/utils/base64.ts",
            "packages/@magic-ext/passkey/src/utils/base64.ts",
            "packages/@magic-ext/react-native-bare-oauth/src/crypto.ts",
            "packages/@magic-ext/react-native-expo-oauth/src/crypto.ts",
            "packages/@magic-ext/wallet-kit/src/lib/validators.ts",
            "packages/@magic-ext/wallet-kit/src/utils/base64.ts",
            "packages/@magic-ext/wallet-kit/src/utils/copy.ts",
            "packages/@magic-ext/wallet-kit/src/utils/device.ts",
            "packages/@magic-ext/webauthn/src/utils/base64.ts",
            "packages/@magic-sdk/provider/src/util/base64-json.ts",
            "packages/@magic-sdk/provider/src/util/semver.js",
            "packages/@magic-sdk/provider/src/util/web-crypto.ts",
            "packages/@magic-sdk/react-native-bare/src/native-crypto/utils/uint8.ts",
        ],
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "magiclabs/magic-js",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "e9fb233763160316989863b4739c4656133d45b0",
        "commit": "e9fb233763160316989863b4739c4656133d45b0",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 200,
        },
    },
    "lonkero": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/lonkero batch/corpora/lonkero/rules
        # Browser-assist extension scanners only (probe surface).
        "path": ROOT / "batch" / "corpora" / "lonkero" / "rules",
        "files": [
            "browser-assist-extension/background.js",
            "browser-assist-extension/bypass-scanner.js",
            "browser-assist-extension/cms-scanner.js",
            "browser-assist-extension/content.js",
            "browser-assist-extension/dom-hooks.js",
            "browser-assist-extension/formfuzzer.js",
            "browser-assist-extension/framework-scanner.js",
            "browser-assist-extension/graphql-fuzzer.js",
            "browser-assist-extension/merlin.js",
            "browser-assist-extension/popup.js",
            "browser-assist-extension/sql-scanner.js",
            "browser-assist-extension/waf-bypass.js",
            "browser-assist-extension/xss-scanner.js",
        ],
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "bountyyfi/lonkero",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "bc1e4859b321e0a6fb125f804b9d7e35975790cc",
        "commit": "bc1e4859b321e0a6fb125f804b9d7e35975790cc",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 200,
        },
    },
    "serviceradar": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/serviceradar batch/corpora/serviceradar/rules
        # First-party js/cli + elixir web-ng assets; exclude third_party, tests, monaco.
        "path": ROOT / "batch" / "corpora" / "serviceradar" / "rules",
        "files": [
            "js/cli/src/args.ts",
            "js/cli/src/auth/credentials.ts",
            "js/cli/src/auth/login.ts",
            "js/cli/src/cli.ts",
            "js/cli/src/dashboard/dev.ts",
            "js/cli/src/dashboard/init.ts",
            "js/cli/src/dashboard/publish.ts",
            "js/cli/src/utils.ts",
            "elixir/web-ng/assets/component/src/DashboardBuilderCanvas.jsx",
            "elixir/web-ng/assets/component/src/DashboardPanelChart.jsx",
            "elixir/web-ng/assets/component/src/RemoteAccessSSHConsole.jsx",
            "elixir/web-ng/assets/component/src/sshEphemeralKeypair.js",
            "elixir/web-ng/assets/js/hooks/CommandPalette.js",
            "elixir/web-ng/assets/js/hooks/DashboardWasmHost.js",
            "elixir/web-ng/assets/js/hooks/MapboxFlowMap.js",
            "elixir/web-ng/assets/js/hooks/OperationsTrafficMap.js",
            "elixir/web-ng/assets/js/hooks/SRQLTimeCookie.js",
            "elixir/web-ng/assets/js/hooks/SpatialSurveyMap.js",
            "elixir/web-ng/assets/js/hooks/charts/FlowDonut.js",
            "elixir/web-ng/assets/js/lib/god_view/rendering_style_edge_telemetry_methods.js",
            "elixir/web-ng/assets/js/lib/remote_desktop/renderer_state.js",
            "elixir/web-ng/assets/js/lib/remote_desktop/webrtc_client.js",
            "elixir/web-ng/assets/js/lib/srql/tokenizer.js",
            "elixir/web-ng/assets/js/utils/chart_hover_geometry.js",
        ],
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "carverauto/serviceradar",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "37859392af3e58b2e1825bbe75091090914277c4",
        "commit": "37859392af3e58b2e1825bbe75091090914277c4",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            # Full clone via symlink is ~1GB; budget is tree size not extract volume.
            "max_disk_mb": 1500,
        },
    },
    "gigachad-grc": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/gigachad-grc batch/corpora/gigachad-grc/rules
        # First-party sanitizers/validators/scanners/mcp evidence tools; no tests/UI.
        "path": ROOT / "batch" / "corpora" / "gigachad-grc" / "rules",
        "files": [
            "services/shared/src/utils/sanitize.ts",
            "services/shared/src/decorators/sanitize.decorator.ts",
            "services/shared/src/logger/sanitizer.ts",
            "services/shared/src/utils/validation.ts",
            "services/shared/src/filters/http-exception.filter.ts",
            "services/controls/src/common/file-validator.service.ts",
            "services/controls/src/training/phishing/phishing.service.ts",
            "services/controls/src/scim/scim.service.ts",
            "services/controls/src/scim/dto/scim.dto.ts",
            "services/controls/src/evidence/evidence.controller.ts",
            "services/tprm/src/security-scanner/security-scanner.service.ts",
            "services/tprm/src/security-scanner/collectors/compliance-collector.ts",
            "services/tprm/src/security-scanner/collectors/web-collector.ts",
            "services/tprm/src/security-scanner/collectors/page-crawler.ts",
            "mcp-servers/grc-compliance/src/tools/policy-validator.ts",
            "mcp-servers/grc-evidence/src/tools/vulnerability-scanner.ts",
            "mcp-servers/grc-evidence/src/tools/google-workspace-evidence.ts",
            "mcp-servers/grc-evidence/src/tools/okta-evidence.ts",
            "services/controls/src/integrations/custom/custom-integration.service.ts",
            "services/controls/src/integrations/connectors/cloud-connectors.ts",
            "services/controls/src/integrations/connectors/gitlab.connector.ts",
            "services/controls/src/integrations/connectors/finance-connectors.ts",
            "services/controls/src/integrations/connectors/utils/google-jwt.ts",
            "services/controls/src/config-as-code/config-files.service.ts",
            "services/tprm/src/contracts/contracts.service.ts",
            "services/trust/src/ai/trust-ai.service.ts",
            "services/shared/src/storage/s3.storage.ts",
            "services/shared/src/storage/azure-blob.storage.ts",
            "services/controls/src/sessions/sessions.service.ts",
            "services/controls/src/collectors/collectors.service.ts",
        ],
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "grcengineering/gigachad-grc",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "d4a39726cad8d8e27e4c0502d1843c3b4180ffbc",
        "commit": "d4a39726cad8d8e27e4c0502d1843c3b4180ffbc",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 500,
        },
    },
    "bartblaze-yara-rules": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/bartblaze-yara-rules/rules batch/corpora/bartblaze-yara-rules/rules
        # bartblaze YARA pack (delta vs admitted yara_rules). Owner-prefixed slug
        # stays case-distinct from VaccinatorSec yara-rules / admitted yara_rules.
        "path": ROOT / "batch" / "corpora" / "bartblaze-yara-rules" / "rules",
        "glob": "**/*.yar,**/*.yara",
        "dialect": "yara",
        "extractor": "yara",
        "repo": "bartblaze/Yara-rules",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "5cc871d82361de8a80d387ec8bbd01fe4258b4a9",
        "commit": "5cc871d82361de8a80d387ec8bbd01fe4258b4a9",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 100,
        },
    },
    "crust": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/crust batch/corpora/crust/rules
        # First-party Go DLP/rules + configscan; no tests / py CVE script.
        "path": ROOT / "batch" / "corpora" / "crust" / "rules",
        "files": [
            "internal/configscan/scan.go",
            "internal/rules/builtin_verify.go",
            "internal/rules/dlp.go",
            "internal/rules/dlp_crypto.go",
            "internal/rules/extractor_powershell.go",
            "internal/rules/lint.go",
        ],
        "dialect": "re2",
        "extractor": "go_regexp",
        "repo": "BakeLens/crust",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "f4a47e2cf2822196275075ab9a2e258b6fa9be8b",
        "commit": "f4a47e2cf2822196275075ab9a2e258b6fa9be8b",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 200,
        },
    },
    "yara-rules": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/vaccinator-yara-rules/rules batch/corpora/yara-rules/rules
        # VaccinatorSec tiny YARA pack (delta vs admitted yara_rules).
        "path": ROOT / "batch" / "corpora" / "yara-rules" / "rules",
        "glob": "**/*.yar,**/*.yara",
        "dialect": "yara",
        "extractor": "yara",
        "repo": "VaccinatorSec/yara-rules",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "1d7c4faed70fae431b8189c904881cc0e12436e6",
        "commit": "1d7c4faed70fae431b8189c904881cc0e12436e6",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 300,
            "redos_wall_s": 60,
            "max_mem_mb": 512,
            "max_disk_mb": 50,
        },
    },
    "ail-yara-rules": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/ail-yara-rules/rules batch/corpora/ail-yara-rules/rules
        # ail-project YARA pack (delta vs admitted yara_rules).
        "path": ROOT / "batch" / "corpora" / "ail-yara-rules" / "rules",
        "glob": "**/*.yar,**/*.yara",
        "dialect": "yara",
        "extractor": "yara",
        "repo": "ail-project/ail-yara-rules",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "8e978d5e70084df6d2fae0727677ec4f60e3e639",
        "commit": "8e978d5e70084df6d2fae0727677ec4f60e3e639",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 600,
            "redos_wall_s": 120,
            "max_mem_mb": 1024,
            "max_disk_mb": 100,
        },
    },
    "xibo-cms": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/xibo-cms batch/corpora/xibo-cms/rules
        # First-party frontend/ui/module-src ecma allowlist; no tests/bundles/vendor/build.
        "path": ROOT / "batch" / "corpora" / "xibo-cms" / "rules",
        "files": [
            "frontend/src/utils/regex.ts",
            "frontend/src/utils/stringUtils.ts",
            "frontend/src/utils/date.ts",
            "frontend/src/schema/command.ts",
            "frontend/src/schema/dataset.ts",
            "frontend/src/schema/display.ts",
            "frontend/src/services/datasetApi.ts",
            "frontend/src/components/ui/forms/DurationInput.tsx",
            "frontend/src/components/ui/forms/TimezoneSelect.tsx",
            "frontend/src/components/editor/EditorHost.tsx",
            "frontend/src/components/help/FeedbackForm.tsx",
            "frontend/src/pages/Administration/Applications/Authorize/AuthorizeApplication.tsx",
            "frontend/src/config/helpKeys.ts",
            "frontend/src/config/publicPath.ts",
            "frontend/src/login/components/LoginCard.tsx",
            "frontend/src/pages/Displays/Commands/components/CommandBuilder/commandStringUtils.ts",
            "frontend/src/pages/Library/Dataset/components/AddAndEditDatasetModal.tsx",
            "frontend/src/pages/Library/Dataset/subPages/Columns/components/CopyDatasetColumnModal.tsx",
            "modules/src/xibo-legacy-template-render.js",
            "modules/src/xibo-substitutes-parser.js",
            "modules/src/xibo-worldclock-render.js",
            "ui/src/core/file-upload.js",
            "ui/src/core/forms.js",
            "ui/src/core/xibo-calendar.js",
            "ui/src/core/xibo-cms.js",
            "ui/src/core/xibo-datatables.js",
            "ui/src/editor-core/element.js",
            "ui/src/editor-core/topbar.js",
            "ui/src/editor-core/widget.js",
            "ui/src/helpers/date-format-helper.js",
            "ui/src/helpers/form-helpers.js",
            "ui/src/helpers/handlebars/replace.js",
            "ui/src/layout-editor/main.js",
            "ui/src/layout-editor/viewer.js",
            "ui/src/playlist-editor/playlist.js",
        ],
        "dialect": "ecma",
        "extractor": "js_precise_dir",
        "repo": "xibosignage/xibo-cms",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "978def55c8e68cab3a50a7ee4725039da753f0a1",
        "commit": "978def55c8e68cab3a50a7ee4725039da753f0a1",
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 500,
        },
    },
    "malcontent": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn /tmp/malcontent/rules batch/corpora/malcontent/rules
        # Chainguard malware-content scanner own rules pack (rules/ only —
        # third_party/ vendored packs excluded by pinning path to rules/).
        # batch-4 GO admit (#261): 1,156 files / 32,908 lines, largest yara
        # corpus in the matrix (probe 19,578 sites incl. third_party).
        "path": ROOT / "batch" / "corpora" / "malcontent" / "rules",
        "glob": "**/*.yar,**/*.yara",
        "dialect": "yara",
        "extractor": "yara",
        "repo": "chainguard-dev/malcontent",
        "security_tool": True,
        "lift_inline": False,
        "corpus_pin": "ea3e83e24676a1678a9522141da29b636c9451ab",
        "commit": "ea3e83e24676a1678a9522141da29b636c9451ab",
        "budget": {
            "max_patterns": 30000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 500,
        },
    },
    "dogfood_shell": {
        "corpus_type": "rule_corpus",
        # Materialize: ln -sfn <merged dogfooding tree> batch/corpora/dogfood_shell/rules
        # The dogfooding universe (usrmanage / fwlive / happycow /
        # hermes-agent-fork) at the P1-frozen pins (dogfooding_novelty_2026-08-12.json).
        # Registration-only this wave (the #149 automation pipeline is separate);
        # the batch run + merged-tree materialization are follow-on.
        # NOTE (cumulative review finding #10): NOT in WAVE_CORPORA — the
        # empty-root fail-closed only guards wave corpora, so a follow-on
        # batch run MUST NOT start until the merged tree is materialized at
        # this path (a 0-site silent pass would read 'go' against an empty
        # tree). Materialize + add to WAVE_CORPORA together.
        "path": ROOT / "batch" / "corpora" / "dogfood_shell" / "rules",
        "dialect": "posix-shell",
        "extractor": "shell_posix",
        "repo": "dogfooding (usrmanage/fwlive/happycow/hermes-agent-fork)",
        "security_tool": False,
        "lift_inline": False,
        "budget": {
            "max_patterns": 5000,
            "max_wall_s": 900,
            "redos_wall_s": 180,
            "max_mem_mb": 2048,
            "max_disk_mb": 500,
        },
    },
    # Wave-3 P5 testdata corpora (#116) — exempt from admission gate_decision.
    "perl_tre": {
        "corpus_type": "testdata",
        # Materialize: ln -sfn /tmp/perl5/t/re batch/corpora/perl_tre/rules
        "path": ROOT / "batch" / "corpora" / "perl_tre" / "rules",
        "full_path": ROOT / "batch" / "corpora" / "perl_tre" / "rules",
        "sample_path": ROOT / "batch" / "corpora" / "perl_tre" / "sample",
        "glob": "*.t,re_tests",
        "dialect": "perl",
        "extractor": "perl_re_tests",
        "repo": "Perl/perl5",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "6aef1e87c1ea274e225828cbc1a6044b54feec44",
        "commit": "6aef1e87c1ea274e225828cbc1a6044b54feec44",
        "expected_files": 81,
        "budget": {
            "max_patterns": 20000,
            "max_wall_s": 1200,
            "max_mem_mb": 1024,
            "max_disk_mb": 100,
        },
    },
    "go_regexp_tests": {
        "corpus_type": "testdata",
        # Materialize: ln -sfn /tmp/golang-go/src/regexp batch/corpora/go_regexp_tests/rules
        "path": ROOT / "batch" / "corpora" / "go_regexp_tests" / "rules",
        "full_path": ROOT / "batch" / "corpora" / "go_regexp_tests" / "rules",
        "sample_path": ROOT / "batch" / "corpora" / "go_regexp_tests" / "sample",
        "glob": "**/*_test.go",
        "dialect": "re2",
        "extractor": "go_regexp_tests",
        "repo": "golang/go",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "e5ec1263ca5e1428d233206b99dc21c38ea2a124",
        "commit": "e5ec1263ca5e1428d233206b99dc21c38ea2a124",
        "expected_files": 9,
        "budget": {
            "max_patterns": 10000,
            "max_wall_s": 600,
            "max_mem_mb": 1024,
            "max_disk_mb": 100,
        },
    },
    "v8_mjsunit": {
        "corpus_type": "testdata",
        # Materialize: ln -sfn /tmp/v8/test/mjsunit batch/corpora/v8_mjsunit/rules
        "path": ROOT / "batch" / "corpora" / "v8_mjsunit" / "rules",
        "full_path": ROOT / "batch" / "corpora" / "v8_mjsunit" / "rules",
        "sample_path": ROOT / "batch" / "corpora" / "v8_mjsunit" / "sample",
        "glob": "**/regexp*.js",
        "dialect": "ecma",
        "extractor": "v8_mjsunit",
        "repo": "v8/v8",
        "security_tool": False,
        "lift_inline": False,
        "corpus_pin": "15ce9d47586c47d1e44c9ddc49366cf4edc509a2",
        "commit": "15ce9d47586c47d1e44c9ddc49366cf4edc509a2",
        "expected_files": 91,
        "budget": {
            "max_patterns": 20000,
            "max_wall_s": 900,
            "max_mem_mb": 1024,
            "max_disk_mb": 200,
        },
    },
}

WAVE_CORPORA = frozenset({
    "trufflehog", "ids_rules", "semgrep_rules",
    "pcre2_testdata", "re2_testdata", "cpython_re", "busybox",
    "yara_rules", "test262", "spamassassin",
    "noseyparker", "shhgit",
    "dompurify", "isemail", "email_addresses", "hippo",
    "everclaw-community-branches",
    "tracecat",
    "octo-server",
    "magic-js",
    "lonkero",
    "serviceradar",
    "gigachad-grc",
    "bartblaze-yara-rules",
    "crust",
    "yara-rules",
    "ail-yara-rules",
    "perl_tre", "go_regexp_tests", "v8_mjsunit",
    "xibo-cms",
    "malcontent",
})


